name: code-coverage
on: push
jobs: 
  code-coverage-job:
    runs-on: ubuntu-latest
    steps:
      - name: actions-learning-pathway
        uses: actions/checkout@v3
      - name: setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: install dependecies
        run: npm install
      - name: run coverage
        run: npm run code-coverage-job
      - name: upload to codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN}}
        
