name: helloWorld
on: push
jobs:
  helloWorld-job:
    runs-on: ubuntu-latest
    steps:
      - name: actions-learning-pathway
        uses: actions/checkout@v3
      - run: echo "$(cat hello-world.txt)"
